### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 03361404585** [emara-geek/real-time-face-detection-using-opencv-with-java#3]
Exception in thread "main" java.lang.UnsatisfiedLinkError: no opencv_java341 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at gui.FaceDetection.main(FaceDetection.java:180)

plz tell me, how to resolve this error

**Comment by catapulveda** [comment]
Debe copiar y pegar el archivo opencv_java341.dll en la carpeta del proyecto en Netbeans.

**Comment by MananGupta00** [comment]
Using openCV 3

After adding -Djava.library.path= "<opencv_java3413.dll path>", no file in this project can run.
Even after completing the code, following error pops up.
Error: Could not find or load main class = C:\Users\manan\AppData\Local\NetBeans\Cache\8.2\executor-snippets\run.xml:53

What i tried:
Made several different projects to debug.
Cleared netbeans cache.
