### ISSUE TITLE
[ WARN:0] Failed to set mediaType (stream 0, (640x480 @ 30) MFVideoFormat_RGB24(unsupported media type)

### ISSUE THREAD

**Issue by MananGupta00** [emara-geek/real-time-face-detection-using-opencv-with-java#7]
On pressing start-->
[ WARN:0] Failed to set mediaType (stream 0, (640x480 @ 30) MFVideoFormat_RGB24(unsupported media type)

Then Repeatedly error is traced by catch statement
Error!!
java.lang.Exception: unknown exception
	at org.opencv.videoio.VideoCapture.retrieve_1(Native Method)
	at org.opencv.videoio.VideoCapture.retrieve(VideoCapture.java:317)
	at gui.FaceDetection$DaemonThread.run(FaceDetection.java:44)    ///////// code at 44th line is 'webSource.retrieve(frame);'
	at java.lang.Thread.run(Thread.java:745)

Using OpenCV 3413
Netbeans IDE 8.2
Changed 2 lines and imports for cv2 to cv3 conversion  : Imgproc.rectangle.....;  Imgcodecs.imencode......;

**Comment by ztswsy9931** [comment]
cap =cv2.VideoCapture(0 + cv2.CAP_DSHOW)
